import React, { useState } from 'react';
import { useRouter } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View, Image } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { useParent, type Language, type ThemePreference } from '@/context/ParentContext';

export default function ProfileSetupScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const router = useRouter();
  const { setLanguage, setTheme, saveParentProfile } = useParent();
  const [name, setName] = useState(''); const [image, setImage] = useState<string | null>(null);
  const [singleParent, setSingleParent] = useState<boolean | null>(null); const [languageChoice, setLanguageChoice] = useState<Language>('EN'); const [themeChoice, setThemeChoice] = useState<ThemePreference>('system');
  const [error, setError] = useState('');
  const pickImage = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError('Photo access is needed to choose a profile image.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, aspect: [1, 1], quality: 0.8 }); if (!result.canceled) setImage(result.assets[0].uri); };
  const save = () => { if (!name.trim()) { setError('Please enter your name.'); return; } if (singleParent === null) { setError('Please choose an option.'); return; } setLanguage(languageChoice); setTheme(themeChoice); saveParentProfile({ name: name.trim(), imageUri: image, singleParent, language: languageChoice, theme: themeChoice }); router.push('/children'); };
  const Choice = ({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) => <Pressable onPress={onPress} style={[styles.choice, { borderColor: selected ? colors.primary : colors.border, backgroundColor: selected ? colors.accent : colors.card }]}><Text style={[styles.choiceText, { color: colors.foreground }]}>{label}</Text>{selected && <Feather name="check-circle" size={19} color={colors.primary} />}</Pressable>;
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 24, paddingBottom: insets.bottom + 28 }]} keyboardShouldPersistTaps="handled">
    <View style={styles.progress}><View style={[styles.progressActive, { backgroundColor: colors.primary }]} /><View style={[styles.progressInactive, { backgroundColor: colors.border }]} /><View style={[styles.progressInactive, { backgroundColor: colors.border }]} /></View>
    <Text style={[styles.kicker, { color: colors.primary }]}>STEP 2 OF 3</Text><Text style={[styles.title, { color: colors.foreground }]}>Tell us about you.</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Your profile helps us personalize Parent+ for your family.</Text>
    <Pressable onPress={pickImage} style={[styles.avatar, { backgroundColor: colors.secondary, borderColor: colors.border }]}>{image ? <Image source={{ uri: image }} style={styles.avatarImage} /> : <Feather name="camera" size={27} color={colors.primary} />}</Pressable><Text style={[styles.photoHint, { color: colors.primary }]}>{image ? 'Change profile image' : 'Add profile image'}</Text>
    <Text style={[styles.label, { color: colors.foreground }]}>Your name</Text><TextInput style={[styles.input, { borderColor: colors.input, backgroundColor: colors.card, color: colors.foreground }]} value={name} onChangeText={setName} placeholder="e.g. Amélie" placeholderTextColor={colors.mutedForeground} />
    <Text style={[styles.label, { color: colors.foreground }]}>Are you a single parent?</Text><View style={styles.row}><Choice label="Yes" selected={singleParent === true} onPress={() => setSingleParent(true)} /><Choice label="No" selected={singleParent === false} onPress={() => setSingleParent(false)} /></View>
    <Text style={[styles.label, { color: colors.foreground }]}>Preferred language</Text><View style={styles.row}><Choice label="English" selected={languageChoice === 'EN'} onPress={() => setLanguageChoice('EN')} /><Choice label="Français" selected={languageChoice === 'FR'} onPress={() => setLanguageChoice('FR')} /></View>
    <Text style={[styles.label, { color: colors.foreground }]}>Theme</Text><View style={styles.row}><Choice label="System" selected={themeChoice === 'system'} onPress={() => setThemeChoice('system')} /><Choice label="Light" selected={themeChoice === 'light'} onPress={() => setThemeChoice('light')} /><Choice label="Dark" selected={themeChoice === 'dark'} onPress={() => setThemeChoice('dark')} /></View>
    {error ? <Text style={[styles.error, { color: colors.destructive }]}>{error}</Text> : null}<Pressable onPress={save} style={[styles.button, { backgroundColor: colors.foreground }]}><Text style={styles.buttonText}>Save and continue</Text><Feather name="arrow-right" size={18} color="#fff" /></Pressable>
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 24 }, progress: { flexDirection: 'row', gap: 6, marginBottom: 28 }, progressActive: { height: 4, borderRadius: 3, flex: 1 }, progressInactive: { height: 4, borderRadius: 3, flex: 1 }, kicker: { fontFamily: 'Inter_700Bold', letterSpacing: 1.2, fontSize: 11, marginBottom: 8 }, title: { fontFamily: 'Inter_700Bold', fontSize: 32 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 20 }, avatar: { alignSelf: 'center', width: 92, height: 92, borderRadius: 46, borderWidth: 1, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, avatarImage: { width: '100%', height: '100%' }, photoHint: { alignSelf: 'center', fontFamily: 'Inter_600SemiBold', fontSize: 13, marginTop: 9, marginBottom: 16 }, label: { fontFamily: 'Inter_600SemiBold', fontSize: 13, marginBottom: 8, marginTop: 7 }, input: { height: 52, borderRadius: 14, borderWidth: 1, paddingHorizontal: 15, fontFamily: 'Inter_400Regular', fontSize: 14 }, row: { flexDirection: 'row', gap: 8 }, choice: { minHeight: 48, borderRadius: 13, borderWidth: 1, paddingHorizontal: 12, flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, choiceText: { fontFamily: 'Inter_500Medium', fontSize: 13 }, error: { fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: 14 }, button: { height: 54, borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, marginTop: 22 }, buttonText: { color: '#fff', fontFamily: 'Inter_600SemiBold', fontSize: 15 } });