export type AgeGroup = '0–2 years' | '3–5 years' | '6–9 years' | '10–14 years';
export type Lesson = {
  id: string;
  age: AgeGroup;
  icon: 'heart' | 'star' | 'compass' | 'users' | 'sun' | 'shield';
  title: { EN: string; FR: string };
  description: { EN: string; FR: string };
  narration: { EN: string; FR: string };
  duration: string;
  quiz: { question: { EN: string; FR: string }; options: { EN: string; FR: string }[]; answer: number };
};

export const AGE_GROUPS: AgeGroup[] = ['0–2 years', '3–5 years', '6–9 years', '10–14 years'];

export const lessons: Lesson[] = [
  { id: 'bonding-babies', age: '0–2 years', icon: 'heart', title: { EN: 'Building a safe bond', FR: 'Créer un lien sécurisant' }, description: { EN: 'Simple ways to respond to your baby with warmth.', FR: 'Des façons simples de répondre à votre bébé avec chaleur.' }, narration: { EN: 'Babies learn trust through repeated, warm responses. Notice their signals, get close, and respond with a calm voice.', FR: 'Les bébés apprennent la confiance grâce à des réponses chaleureuses et répétées. Observez leurs signaux et répondez calmement.' }, duration: '4 min', quiz: { question: { EN: 'What helps a baby feel safe?', FR: 'Qu’est-ce qui aide un bébé à se sentir en sécurité ?' }, options: [{ EN: 'Warm, consistent responses', FR: 'Des réponses chaleureuses et régulières' }, { EN: 'Ignoring every cry', FR: 'Ignorer chaque pleur' }, { EN: 'Using fear', FR: 'Faire peur' }], answer: 0 } },
  { id: 'play-together', age: '0–2 years', icon: 'star', title: { EN: 'Play is communication', FR: 'Le jeu est une communication' }, description: { EN: 'Connect through songs, faces and everyday play.', FR: 'Créer un lien par les chansons et le jeu quotidien.' }, narration: { EN: 'Your face, voice, and touch are your baby’s first learning tools. Follow their interest and enjoy a few focused minutes together.', FR: 'Votre visage, votre voix et votre toucher sont les premiers outils d’apprentissage de votre bébé.' }, duration: '5 min', quiz: { question: { EN: 'During play, what should you follow?', FR: 'Pendant le jeu, que devez-vous suivre ?' }, options: [{ EN: 'Your child’s interest', FR: 'L’intérêt de votre enfant' }, { EN: 'A strict timer', FR: 'Un temps strict' }, { EN: 'Only your own plan', FR: 'Seulement votre propre plan' }], answer: 0 } },
  { id: 'big-feelings', age: '3–5 years', icon: 'heart', title: { EN: 'Big feelings, safe spaces', FR: 'De grandes émotions, un espace sûr' }, description: { EN: 'Help your child name feelings and find calm.', FR: 'Aider votre enfant à nommer ses émotions et à se calmer.' }, narration: { EN: 'When feelings are big, your calm presence is a safe anchor. Name the feeling without judgement, then offer a small choice.', FR: 'Quand les émotions sont fortes, votre présence calme est un point d’ancrage. Nommez l’émotion sans jugement.' }, duration: '6 min', quiz: { question: { EN: 'What comes before correction?', FR: 'Que faire avant de corriger ?' }, options: [{ EN: 'Connection', FR: 'La connexion' }, { EN: 'A threat', FR: 'Une menace' }, { EN: 'A long lecture', FR: 'Un long discours' }], answer: 0 } },
  { id: 'listen-first', age: '3–5 years', icon: 'users', title: { EN: 'Listen before you lead', FR: 'Écouter avant de guider' }, description: { EN: 'Build cooperation through attentive listening.', FR: 'Favoriser la coopération par une écoute attentive.' }, narration: { EN: 'Get down to your child’s level, listen for the need underneath the behaviour, and reflect back what you heard.', FR: 'Mettez-vous au niveau de votre enfant, écoutez son besoin et reformulez ce que vous avez entendu.' }, duration: '4 min', quiz: { question: { EN: 'What can listening help you understand?', FR: 'Que peut vous aider à comprendre l’écoute ?' }, options: [{ EN: 'The need behind behaviour', FR: 'Le besoin derrière le comportement' }, { EN: 'Nothing useful', FR: 'Rien d’utile' }, { EN: 'How to punish faster', FR: 'Comment punir plus vite' }], answer: 0 } },
  { id: 'positive-discipline', age: '6–9 years', icon: 'compass', title: { EN: 'Guidance without fear', FR: 'Guider sans faire peur' }, description: { EN: 'Set clear limits while protecting connection.', FR: 'Fixer des limites claires tout en gardant le lien.' }, narration: { EN: 'Children need boundaries they can understand. State the limit briefly, explain why, and show what they can do next.', FR: 'Les enfants ont besoin de limites compréhensibles. Énoncez la limite brièvement et montrez la prochaine étape.' }, duration: '5 min', quiz: { question: { EN: 'A helpful limit should be…', FR: 'Une limite utile doit être…' }, options: [{ EN: 'Clear and calm', FR: 'Claire et calme' }, { EN: 'Shameful', FR: 'Humiliante' }, { EN: 'Different every time', FR: 'Différente à chaque fois' }], answer: 0 } },
  { id: 'learning-confidence', age: '6–9 years', icon: 'star', title: { EN: 'Grow learning confidence', FR: 'Développer la confiance pour apprendre' }, description: { EN: 'Encourage effort, questions and curiosity.', FR: 'Encourager l’effort, les questions et la curiosité.' }, narration: { EN: 'Praise the process instead of only the result. Ask what your child tried, what they noticed, and what they want to try next.', FR: 'Félicitez le processus plutôt que le seul résultat. Demandez ce que votre enfant a essayé et remarqué.' }, duration: '6 min', quiz: { question: { EN: 'What is useful to praise?', FR: 'Que peut-on féliciter utilement ?' }, options: [{ EN: 'Effort and strategies', FR: 'L’effort et les stratégies' }, { EN: 'Only perfect results', FR: 'Seulement les résultats parfaits' }, { EN: 'Giving up', FR: 'Abandonner' }], answer: 0 } },
  { id: 'teen-connection', age: '10–14 years', icon: 'users', title: { EN: 'Stay connected as they grow', FR: 'Rester proche en grandissant' }, description: { EN: 'Respect growing independence while staying present.', FR: 'Respecter l’autonomie grandissante tout en restant présent.' }, narration: { EN: 'Teenagers still need a safe relationship. Make space for their view, protect privacy, and keep a door open for difficult conversations.', FR: 'Les adolescents ont toujours besoin d’une relation sécurisante. Faites une place à leur point de vue et gardez le dialogue ouvert.' }, duration: '7 min', quiz: { question: { EN: 'What keeps communication open?', FR: 'Qu’est-ce qui garde la communication ouverte ?' }, options: [{ EN: 'Respect and curiosity', FR: 'Le respect et la curiosité' }, { EN: 'Public embarrassment', FR: 'L’humiliation publique' }, { EN: 'Never listening', FR: 'Ne jamais écouter' }], answer: 0 } },
  { id: 'teen-safe-space', age: '10–14 years', icon: 'shield', title: { EN: 'A safe home for hard moments', FR: 'Un foyer sûr dans les moments difficiles' }, description: { EN: 'Create a home where concerns can be shared.', FR: 'Créer un foyer où les inquiétudes peuvent être partagées.' }, narration: { EN: 'Safety grows when young people know they can tell you the truth without being shamed. Listen first, then work on solutions together.', FR: 'La sécurité grandit quand les jeunes savent qu’ils peuvent dire la vérité sans être humiliés. Écoutez d’abord, puis cherchez ensemble.' }, duration: '6 min', quiz: { question: { EN: 'What should come first when a teen shares a concern?', FR: 'Que faire en premier quand un adolescent partage une inquiétude ?' }, options: [{ EN: 'Listen without shame', FR: 'Écouter sans humilier' }, { EN: 'Interrupt immediately', FR: 'Interrompre immédiatement' }, { EN: 'Share it publicly', FR: 'La partager publiquement' }], answer: 0 } },
];

export function lessonsForAge(age: string) {
  return lessons.filter((lesson) => lesson.age === age);
}