import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Feather } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { useParent, type ChildProfile } from '@/context/ParentContext';

const situations = [
  { title: 'My child is having a meltdown', icon: 'cloud-rain' as const, guide: 'Pause. Take one slow breath. Move close enough for your child to feel safe, then name the feeling.' },
  { title: 'We keep arguing at home', icon: 'message-circle' as const, guide: 'Lower the pace. Use fewer words, listen for the need underneath the behaviour, and agree on one small next step.' },
  { title: 'My child will not listen', icon: 'volume-2' as const, guide: 'Get their attention gently, say what you need in one clear sentence, and offer two simple choices.' },
  { title: 'I feel overwhelmed', icon: 'battery' as const, guide: 'You deserve care too. If it is safe, take a short pause and ask a trusted adult for support.' },
];

function ageGroup(age: string) { const value = Number.parseInt(age, 10); if (value <= 5) return 'early years'; if (value <= 9) return 'primary years'; return 'pre-teen years'; }
function personalizedGuide(child: ChildProfile, points: number) { const group = ageGroup(child.age); const opening = group === 'early years' ? 'Keep routines short, warm, and predictable.' : group === 'primary years' ? 'Give your child room to practise independence while staying close.' : 'Respect growing independence and keep the door open for honest conversations.'; const focus = child.educationLevel === 'Nursery' ? 'Use play, pictures, and one-step instructions.' : child.educationLevel === 'Primary' ? 'Ask what they noticed and praise effort rather than only results.' : 'Invite their perspective before offering advice.'; return points >= 5 ? opening + ' ' + focus + ' Your PPC-supported guide for ' + child.name + ' suggests one calm check-in today, followed by a specific question about what felt easy or difficult.' : opening + ' ' + focus + ' Complete 15 parental-guided courses to unlock 5 PPC points and a deeper guide for ' + child.name + '.'; }

export default function SupportScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets();
  const { children, ppcPoints, language } = useParent();
  const [selected, setSelected] = useState<string | null>(null); const [selectedChild, setSelectedChild] = useState<ChildProfile | null>(children[0] ?? null); const [callTopic, setCallTopic] = useState(''); const [callRequested, setCallRequested] = useState(false); const [feedback, setFeedback] = useState(''); const [feedbackSent, setFeedbackSent] = useState(false);
  const copy = language === 'FR' ? { kicker: 'SOUTIEN PRATIQUE', title: 'Vous n’êtes pas seul.', subtitle: 'Un soutien calme et pratique pour votre famille.', expert: 'Parler à un expert', feedback: 'Votre avis', guide: 'Guide parental personnalisé', choose: 'Choisissez un enfant', points: 'points PPC', request: 'Demander un appel vidéo', sent: 'Demande envoyée', send: 'Envoyer un commentaire' } : { kicker: 'PRACTICAL SUPPORT', title: 'You’re not alone in this.', subtitle: 'Calm, practical support for your family.', expert: 'Talk to an expert', feedback: 'Share your feedback', guide: 'Personalized parental guide', choose: 'Choose a child', points: 'PPC points', request: 'Request a video call', sent: 'Request sent', send: 'Send feedback' };
  const submitFeedback = () => { if (!feedback.trim()) return; void AsyncStorage.setItem('parent-feedback', feedback.trim()); setFeedbackSent(true); setFeedback(''); };
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 22 }]} keyboardShouldPersistTaps="handled">
    <Text style={[styles.kicker, { color: colors.primary }]}>{copy.kicker}</Text><Text style={[styles.title, { color: colors.foreground }]}>{copy.title}</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>{copy.subtitle}</Text>
    {situations.map((item) => { const isOpen = selected === item.title; return <Pressable key={item.title} onPress={() => setSelected(isOpen ? null : item.title)} style={[styles.item, { backgroundColor: colors.card, borderColor: isOpen ? colors.primary : colors.border }]}><View style={[styles.itemIcon, { backgroundColor: colors.secondary }]}><Feather name={item.icon} size={20} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.itemTitle, { color: colors.foreground }]}>{item.title}</Text>{isOpen && <Text style={[styles.guide, { color: colors.mutedForeground }]}>{item.guide}</Text>}</View><Feather name={isOpen ? 'chevron-up' : 'chevron-down'} size={19} color={colors.mutedForeground} /></Pressable>; })}
    <View style={[styles.section, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={styles.sectionHeading}><View style={[styles.sectionIcon, { backgroundColor: colors.secondary }]}><Feather name="video" size={19} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{copy.expert}</Text><Text style={[styles.sectionSub, { color: colors.mutedForeground }]}>Connect with a parenting professional by video.</Text></View></View><TextInput value={callTopic} onChangeText={setCallTopic} placeholder="What would you like to discuss?" placeholderTextColor={colors.mutedForeground} style={[styles.input, { borderColor: colors.input, color: colors.foreground }]} multiline /><Pressable onPress={() => { if (callTopic.trim()) setCallRequested(true); }} style={[styles.action, { backgroundColor: colors.foreground }]}><Feather name={callRequested ? 'check' : 'video'} size={17} color="#fff" /><Text style={styles.actionText}>{callRequested ? copy.sent : copy.request}</Text></Pressable></View>
    <View style={[styles.section, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={styles.sectionHeading}><View style={[styles.sectionIcon, { backgroundColor: colors.accent }]}><Feather name="cpu" size={19} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{copy.guide}</Text><Text style={[styles.sectionSub, { color: colors.mutedForeground }]}>AI guidance shaped by age, school level, and your course progress.</Text></View></View><Text style={[styles.points, { color: colors.primary }]}>{ppcPoints} {copy.points}</Text><Text style={[styles.label, { color: colors.foreground }]}>{copy.choose}</Text><View style={styles.wrap}>{children.map((child) => <Pressable key={child.name} onPress={() => setSelectedChild(child)} style={[styles.childChip, { borderColor: selectedChild?.name === child.name ? colors.primary : colors.border, backgroundColor: selectedChild?.name === child.name ? colors.accent : colors.background }]}><Text style={[styles.chipText, { color: colors.foreground }]}>{child.name}</Text></Pressable>)}</View>{selectedChild ? <View style={[styles.aiCard, { backgroundColor: colors.secondary }]}><Text style={[styles.aiLabel, { color: colors.primary }]}>PARENT+ AI</Text><Text style={[styles.aiText, { color: colors.foreground }]}>{personalizedGuide(selectedChild, ppcPoints)}</Text></View> : <Text style={[styles.sectionSub, { color: colors.mutedForeground }]}>Add a child during setup to receive a guide.</Text>}</View>
    <View style={[styles.section, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={styles.sectionHeading}><View style={[styles.sectionIcon, { backgroundColor: colors.secondary }]}><Feather name="message-square" size={19} color={colors.primary} /></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{copy.feedback}</Text></View><TextInput value={feedback} onChangeText={setFeedback} placeholder="Tell us what would make Parent+ better..." placeholderTextColor={colors.mutedForeground} style={[styles.input, styles.feedbackInput, { borderColor: colors.input, color: colors.foreground }]} multiline /><Pressable onPress={submitFeedback} style={[styles.outlineAction, { borderColor: colors.primary }]}><Text style={[styles.outlineText, { color: colors.primary }]}>{feedbackSent ? 'Thanks for your feedback' : copy.send}</Text></Pressable></View>
    <View style={[styles.safety, { backgroundColor: colors.accent }]}><Feather name="shield" size={18} color={colors.primary} /><Text style={[styles.safetyText, { color: colors.accentForeground }]}>This guidance is educational and not a replacement for emergency services or a qualified professional.</Text></View>
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, paddingBottom: 110 }, kicker: { fontFamily: 'Inter_700Bold', letterSpacing: 1.2, fontSize: 11, marginBottom: 8 }, title: { fontFamily: 'Inter_700Bold', fontSize: 30, lineHeight: 36 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 22 }, item: { borderWidth: 1, borderRadius: 17, padding: 15, marginBottom: 11, flexDirection: 'row', alignItems: 'flex-start', gap: 12 }, itemIcon: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, itemTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 15, lineHeight: 21, paddingTop: 9 }, guide: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 20, marginTop: 10, paddingRight: 5 }, section: { borderWidth: 1, borderRadius: 17, padding: 15, marginTop: 4, marginBottom: 12 }, sectionHeading: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 13 }, sectionIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, sectionTitle: { fontFamily: 'Inter_700Bold', fontSize: 16 }, sectionSub: { fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, marginTop: 3 }, input: { minHeight: 48, borderWidth: 1, borderRadius: 12, padding: 12, fontFamily: 'Inter_400Regular', fontSize: 13, marginBottom: 10 }, feedbackInput: { minHeight: 88, textAlignVertical: 'top' }, action: { height: 47, borderRadius: 12, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center' }, actionText: { color: '#fff', fontFamily: 'Inter_600SemiBold', fontSize: 13 }, outlineAction: { height: 46, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, outlineText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, points: { fontFamily: 'Inter_700Bold', fontSize: 13, marginBottom: 12 }, label: { fontFamily: 'Inter_600SemiBold', fontSize: 12, marginBottom: 8 }, wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, childChip: { borderWidth: 1, borderRadius: 11, paddingHorizontal: 14, paddingVertical: 10 }, chipText: { fontFamily: 'Inter_500Medium', fontSize: 12 }, aiCard: { borderRadius: 13, padding: 13, marginTop: 14 }, aiLabel: { fontFamily: 'Inter_700Bold', letterSpacing: 1, fontSize: 10 }, aiText: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 20, marginTop: 6 }, safety: { borderRadius: 15, padding: 15, flexDirection: 'row', gap: 10, marginTop: 2, alignItems: 'flex-start' }, safetyText: { flex: 1, fontFamily: 'Inter_500Medium', fontSize: 12, lineHeight: 18 } });